// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe2wrt-cbIgXnRdOisW-fHi3hQV3-mW9o',
    appId: '1:80337691487:web:fd6421db0fbd3e19974cea',
    messagingSenderId: '80337691487',
    projectId: 'aura-bloom-9a813',
    authDomain: 'aura-bloom-9a813.firebaseapp.com',
    storageBucket: 'aura-bloom-9a813.firebasestorage.app',
    measurementId: 'G-6GHQCVQE48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnS-AQyrOUUsDRFCltVY0VeZbCfDpwQ2s',
    appId: '1:80337691487:android:8b72a2bdb4974783974cea',
    messagingSenderId: '80337691487',
    projectId: 'aura-bloom-9a813',
    storageBucket: 'aura-bloom-9a813.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI5eiDdAQ1VWPeFH2sTFXFZzxK2Q-fbrQ',
    appId: '1:80337691487:ios:2d0fc2b659d61aaa974cea',
    messagingSenderId: '80337691487',
    projectId: 'aura-bloom-9a813',
    storageBucket: 'aura-bloom-9a813.firebasestorage.app',
    iosBundleId: 'com.aurabloom.app',
  );
}
